"""empty message

Revision ID: 3d249966cce0
Revises: c84798c59af1
Create Date: 2023-05-24 00:03:35.909685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d249966cce0'
down_revision = 'c84798c59af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
