"""empty message

Revision ID: 911438a345e8
Revises: 1c775a355e89
Create Date: 2023-05-23 22:33:12.838716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '911438a345e8'
down_revision = '1c775a355e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=900), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
